import { ClientWrapper } from "@/components/templates/layout/ClientWrapper";
import MainLayout from "@/components/templates/layout/MainLayout";
import "@styles/globals.css";
import { Cairo } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const cairo = Cairo({
  variable: "--cairo",
  style: "normal",
  subsets: ["latin", "latin-ext"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html dir="rtl" lang="en">
      <body
        className={cairo.className + " bg-background text-background-content"}
      >
        <ClientWrapper>
          <MainLayout>{children}</MainLayout>
        </ClientWrapper>
      </body>
    </html>
  );
}
