import { ClientWrapper } from "@/components/templates/layout/ClientWrapper";
import MainLayout from "@/components/templates/layout/MainLayout";
import "@styles/globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html dir="rtl" lang="en">
      <body
        className={inter.className + " bg-background text-background-content"}
      >
        <ClientWrapper>
          <MainLayout>{children}</MainLayout>
        </ClientWrapper>
      </body>
    </html>
  );
}
